export enum MenuLabels {
  CAPACITACION = "SIMULADORES",
  CETIFICADO = "CURSOS",
  OTRAS_CONSULTAS = "INFO GRATIS",
  
}

export enum MenuLabelsCapacitacion {
  RETROXACAVADORA = "SIMULADOR 1",
  EXCAVADORA = "SIMULADOR 2",
  CARGADOR_FRONTAL = "SIMULADOR 3",
  MOTONIVELEADORA = "SIMULADOR 4",
  TRACTOR_SOBRE_ORUGAS = "SIMULADOR 5",
  RODILLO_COMPACTADOR = "SIMULADOR 6",
  MINICARGADOR = "SIMULADOR 7",
  MONTACARGAS = "SIMULADOR 8",
}

export enum MenuLabelsCertificado {
  COMPETENCIAS_LABORALES = "CURSO 1",
  BENEFICIOS = "CURSO 2",
  REQUISITOS = "CURSO 3",
}

export enum MenuLabelsOtrasConsultas {
  DIRECCION_HORARIO = "PDF DE EXCAVADORA",
  CONSULTA_SPECIFICA = "PDF DE CARGADORES",
  REDES_SOCIALES = "PDF DE MOTONIVELADORAS",
  CALIFICAR_BOT = "PDF DE CAMIONES",
  ENVIAR_PDF = "PDF DIVERSOS",
}

export enum MainBack {
  MAIN_BACK = "Regresar al menú principal",
}
