export enum MenuLabels {
  CAPACITACION = "CAPACITACION 🧑🏻‍🏫👷🏼‍♂️",
  CETIFICADO = "CERTIFICACION 🥇📜",
  OTRAS_CONSULTAS = "OTRAS CONSULTAS 📝❓",
  
}

export enum MenuLabelsCapacitacion {
  RETROXACAVADORA = "RETROEXCAVADORA",
  EXCAVADORA = "EXCAVADORA",
  CARGADOR_FRONTAL = "CARGADOR FRONTAL",
  MOTONIVELEADORA = "MOTONIVELADORA",
  TRACTOR_SOBRE_ORUGAS = "TRACTOR SOBRE ORUGAS",
  RODILLO_COMPACTADOR = "RODILLO COMPACTADOR",
  MINICARGADOR = "MINICARGADOR",
  MONTACARGAS = "MONTACARGAS",
}

export enum MenuLabelsCertificado {
  COMPETENCIAS_LABORALES = "COMPETENCIAS LABORALES",
  BENEFICIOS = "BENEFICIOS",
  REQUISITOS = "REQUISITOS",
  MAQUINAS_CERTIFICABLES = "MAQUINAS CERTIFICABLES",
  NORMALIZACION = "NORMALIZACION",
}

export enum MenuLabelsOtrasConsultas {
  DIRECCION_HORARIO = "DIRECCION & HORARIO",
  CONSULTA_SPECIFICA = "CONSULTA ESPECIFICAS",
  REDES_SOCIALES = "REDES & PROMOCIONES",
  CALIFICAR_BOT = "ALQUILER DE SIMULADORES",
  ENVIAR_PDF = "REDES & PROMOCIONES",
}

export enum MainBack {
  MAIN_BACK = "Regresar al menú principal",
}
